# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ deploy-contracts ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install project dependencies
        run: npm install

      - name: Compile contracts
        run: npm run compile-contracts

      - name: Run tests
        run: npm test

      - name: Deploy contracts
        env:
          ROPSTEN_URL: ${{ secrets.ROPSTEN_URL }}
          ROPSTEN_PRIVATEKEY: ${{ secrets.ROPSTEN_PRIVATEKEY }}
        run: npm run deploy-ropsten
